services:
  postgres_db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${PG_USER}"]
      interval: 5s
      retries: 5
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - "${PG_DATA_PATH}:/var/lib/postgresql/data"
