// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"
)

type User struct {
	Username       string
	HashedPassword string
	CreatedAt      time.Time
}
