// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: url.sql

package repository

import (
	"context"
)

const checkShortUrl = `-- name: CheckShortUrl :one
select exists (select 1 from short_urls where short_url = $1 for update)
`

func (q *Queries) CheckShortUrl(ctx context.Context, shortUrl string) (bool, error) {
	row := q.queryRow(ctx, q.checkShortUrlStmt, checkShortUrl, shortUrl)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getShortUrlLength = `-- name: GetShortUrlLength :one
select length from short_url_length for update
`

func (q *Queries) GetShortUrlLength(ctx context.Context) (int32, error) {
	row := q.queryRow(ctx, q.getShortUrlLengthStmt, getShortUrlLength)
	var length int32
	err := row.Scan(&length)
	return length, err
}

const incrementShortUrlLength = `-- name: IncrementShortUrlLength :one
update short_url_length 
set 
    length = length + 1,
    last_update = now()
returning length
`

func (q *Queries) IncrementShortUrlLength(ctx context.Context) (int32, error) {
	row := q.queryRow(ctx, q.incrementShortUrlLengthStmt, incrementShortUrlLength)
	var length int32
	err := row.Scan(&length)
	return length, err
}

const insertShortUrl = `-- name: InsertShortUrl :exec
insert into short_urls (username, long_url, short_url)
values ($1, $2, $3)
`

type InsertShortUrlParams struct {
	Username string
	LongUrl  string
	ShortUrl string
}

func (q *Queries) InsertShortUrl(ctx context.Context, arg InsertShortUrlParams) error {
	_, err := q.exec(ctx, q.insertShortUrlStmt, insertShortUrl, arg.Username, arg.LongUrl, arg.ShortUrl)
	return err
}
