// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres_repo

import (
	"time"
)

type ShortUrl struct {
	Username  string
	LongUrl   string
	ShortUrl  string
	CreatedAt time.Time
}

type ShortUrlLength struct {
	Length     int32
	LastUpdate time.Time
}

type UrlVisit struct {
	ShortUrl  string
	VisitorIp string
	VisitedAt time.Time
}

type User struct {
	Username       string
	HashedPassword string
	CreatedAt      time.Time
}
